# Generated by Django 5.2.12 on 2026-04-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="notification_subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="parking_event",
            fields=[
                (
                    "event_id",
                    models.AutoField(
                        db_column="eventID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("PARKED", "Parked"), ("LEFT", "Left")],
                        db_column="eventType",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "parking_parkingevent",
            },
        ),
        migrations.CreateModel(
            name="parking_lot",
            fields=[
                (
                    "lot_id",
                    models.AutoField(
                        db_column="lotID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("total_spaces", models.IntegerField(db_column="totalSpaces")),
                ("available_spaces", models.IntegerField(db_column="availableSpaces")),
                ("catalog_id", models.IntegerField(db_column="catalogID", default=1)),
            ],
            options={
                "db_table": "parking_parkinglot",
            },
        ),
    ]
