# Generated by Django 4.2.7 on 2026-03-06 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('lotID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('totalSpaces', models.IntegerField()),
                ('availableSpaces', models.IntegerField()),
                ('catalogID', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingEvent',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventType', models.CharField(choices=[('PARKED', 'Parked'), ('LEFT', 'Left')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
