# Generated by Django 5.2.12 on 2026-04-08 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification_subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="parking_event",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="parking_event",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parking.parking_lot"
            ),
        ),
        migrations.AddField(
            model_name="notification_subscription",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parking.parking_lot"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notification_subscription",
            unique_together={("user", "lot")},
        ),
    ]
