# Generated by Django 4.2.7 on 2026-03-06 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsReport',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('dateRange', models.CharField(max_length=100)),
                ('occupancyRates', models.FloatField()),
                ('peakTimes', models.CharField(max_length=100)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot')),
            ],
        ),
    ]
