# Generated by Django 5.2.12 on 2026-04-08 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="admin",
            fields=[
                (
                    "admin_id",
                    models.AutoField(
                        db_column="adminID", primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(db_column="firstName", max_length=100)),
                ("last_name", models.CharField(db_column="lastName", max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="statistics_report",
            fields=[
                (
                    "report_id",
                    models.AutoField(
                        db_column="reportID", primary_key=True, serialize=False
                    ),
                ),
                ("date_range", models.JSONField(db_column="dateRange")),
                ("statistics", models.JSONField()),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Statistics Report",
                "verbose_name_plural": "Statistics Reports",
                "db_table": "adminpanel_statisticsreport",
                "ordering": ["-generated_at"],
            },
        ),
    ]
